import type {
  AssignmentSummary,
  ClassSummary,
  DashboardModule,
  DemoAccount,
  ExamSummary,
  NotificationItem,
  OmrBatchSummary,
  ProgressPoint,
  QuestionSummary,
  RemarkSummary,
  ResultDetailRow,
  ResultSummary,
  StudentRecord,
  UserSummary,
} from '../types/domain';

export const demoAccounts: DemoAccount[] = [
  {
    email: 'teacher@edu.vn',
    password: '123456',
    role: 'TEACHER',
    profileName: 'Nguyễn Văn A',
  },
  {
    email: 'student@edu.vn',
    password: '123456',
    role: 'STUDENT',
    profileName: 'Trần Thị B',
  },
  {
    email: 'admin@edu.vn',
    password: '123456',
    role: 'ADMIN',
    profileName: 'Admin EduScan',
  },
];

export const teacherDashboardModules: DashboardModule[] = [
  { id: 'classes', count: '5 lớp', gradient: ['#5B5BD6', '#7C5CFC'] },
  { id: 'exams', count: '12 đề', gradient: ['#3B82F6', '#06B6D4'] },
  { id: 'omr', count: '3 đợt', gradient: ['#8B5CF6', '#A855F7'] },
  { id: 'remarks', count: '3 yêu cầu', gradient: ['#F59E0B', '#F97316'] },
  { id: 'questions', count: '48 câu', gradient: ['#10B981', '#14B8A6'] },
  { id: 'stats', count: 'Xem báo cáo', gradient: ['#EC4899', '#F43F5E'] },
];

export const studentDashboardModules: DashboardModule[] = [
  { id: 'classes', subtext: '4 lớp đang học', gradient: ['#5B5BD6', '#7C5CFC'] },
  { id: 'results', subtext: '12 bài thi', gradient: ['#3B82F6', '#06B6D4'] },
  { id: 'assignments', subtext: '3 chưa nộp', gradient: ['#10B981', '#14B8A6'] },
  { id: 'remarks', subtext: '1 đang chờ', gradient: ['#F59E0B', '#F97316'] },
  { id: 'progress', subtext: 'TB: 7.8', gradient: ['#EC4899', '#F43F5E'] },
];

export const adminDashboardModules: DashboardModule[] = [
  { id: 'users', subtext: '156 người dùng', gradient: ['#5B5BD6', '#7C5CFC'] },
  { id: 'classes', subtext: '18 lớp đang hoạt động', gradient: ['#3B82F6', '#06B6D4'] },
  { id: 'stats', subtext: 'Xem báo cáo', gradient: ['#10B981', '#14B8A6'] },
  { id: 'settings', subtext: 'Hệ thống', gradient: ['#F59E0B', '#F97316'] },
];

export const teacherClasses: ClassSummary[] = [
  {
    id: '1',
    name: 'Toán cao cấp',
    subject: 'Toán',
    schoolYear: '2025-2026',
    code: 'EDU-ABC123',
    studentCount: 35,
  },
  {
    id: '2',
    name: 'Vật lý đại cương',
    subject: 'Vật lý',
    schoolYear: '2025-2026',
    code: 'EDU-XYZ789',
    studentCount: 42,
  },
  {
    id: '3',
    name: 'Hoá học hữu cơ',
    subject: 'Hoá học',
    schoolYear: '2025-2026',
    code: 'EDU-QWE456',
    studentCount: 28,
  },
  {
    id: '4',
    name: 'Sinh học tế bào',
    subject: 'Sinh học',
    schoolYear: '2025-2026',
    code: 'EDU-RTY321',
    studentCount: 31,
  },
];

export const classStudents: StudentRecord[] = [
  {
    id: '1',
    name: 'Trần Thị B',
    studentCode: 'STU001',
    email: 'b@example.com',
    isActive: true,
    joinedAt: '01/09/2025',
  },
  {
    id: '2',
    name: 'Lê Văn C',
    studentCode: 'STU002',
    email: 'c@example.com',
    isActive: true,
    joinedAt: '02/09/2025',
  },
  {
    id: '3',
    name: 'Phạm Minh D',
    studentCode: 'STU003',
    email: 'd@example.com',
    isActive: true,
    joinedAt: '03/09/2025',
  },
  {
    id: '4',
    name: 'Nguyễn Hoàng E',
    studentCode: 'STU004',
    email: 'e@example.com',
    isActive: false,
    joinedAt: '04/09/2025',
  },
];

export const teacherAssignments: AssignmentSummary[] = [
  {
    id: '1',
    title: 'Bài tập chương 3',
    description: 'Giải bài tập trang 45–48',
    deadline: '2025-04-25T23:59:00',
    classNames: ['Toán 10A1'],
    submitCount: 28,
    totalStudents: 35,
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: false,
    latePenaltyPct: 0,
  },
  {
    id: '2',
    title: 'Bài kiểm tra 15 phút',
    description: 'Ôn tập lý thuyết chương 2',
    deadline: '2025-05-03T23:59:00',
    classNames: ['Toán 10A1'],
    submitCount: 12,
    totalStudents: 35,
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: false,
    latePenaltyPct: 0,
  },
  {
    id: '3',
    title: 'Luận văn ngắn số 1',
    description: '',
    deadline: '2025-05-10T23:59:00',
    classNames: ['Toán 10A1'],
    submitCount: 5,
    totalStudents: 35,
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: false,
    latePenaltyPct: 0,
  },
];

export const teacherExams: ExamSummary[] = [
  {
    id: '1',
    title: 'Giữa kỳ Toán',
    maxScore: 10,
    variantCount: 2,
    classNames: ['Toán 10A1'],
    hasSubmissions: true,
    questionCount: 40,
  },
  {
    id: '2',
    title: 'Cuối kỳ Vật lý',
    maxScore: 10,
    variantCount: 4,
    classNames: ['Vật lý 11A2', 'Vật lý 11A3'],
    hasSubmissions: false,
    questionCount: 50,
  },
  {
    id: '3',
    title: 'Kiểm tra 15 phút Hoá',
    maxScore: 10,
    variantCount: 1,
    classNames: ['Hoá 12A1'],
    hasSubmissions: false,
    questionCount: 20,
  },
];

export const omrBatches: OmrBatchSummary[] = [
  {
    id: '1',
    examTitle: 'Giữa kỳ Toán',
    status: 'COMPLETED',
    totalFiles: 35,
    successCount: 33,
    failedCount: 2,
    progressPercentage: 100,
    createdAt: '2025-04-15',
  },
  {
    id: '2',
    examTitle: 'Cuối kỳ Vật lý',
    status: 'PROCESSING',
    totalFiles: 42,
    successCount: 28,
    failedCount: 0,
    progressPercentage: 67,
    createdAt: '2025-04-18',
  },
  {
    id: '3',
    examTitle: 'Kiểm tra Hoá',
    status: 'PENDING',
    totalFiles: 20,
    successCount: 0,
    failedCount: 0,
    progressPercentage: 0,
    createdAt: '2025-04-19',
  },
];

export const teacherRemarks: RemarkSummary[] = [
  {
    id: '1',
    studentName: 'Trần Thị B',
    studentCode: 'STU001',
    examTitle: 'Giữa kỳ Toán',
    questionNumber: 5,
    reason: 'Em chọn đáp án A nhưng hệ thống nhận là B',
    status: 'PENDING',
    createdAt: '2025-04-18',
  },
  {
    id: '2',
    studentName: 'Lê Văn C',
    studentCode: 'STU002',
    examTitle: 'Cuối kỳ Vật lý',
    questionNumber: 12,
    reason: 'Câu này em tô rõ ràng mà bị nhận sai',
    status: 'PENDING',
    createdAt: '2025-04-17',
  },
  {
    id: '3',
    studentName: 'Phạm Minh D',
    studentCode: 'STU003',
    examTitle: 'Giữa kỳ Toán',
    questionNumber: 8,
    reason: 'Phần tô bị mờ, xin xem lại',
    status: 'APPROVED',
    createdAt: '2025-04-16',
  },
];

export const questionBank: QuestionSummary[] = [
  {
    id: '1',
    content: 'Phương trình bậc hai ax² + bx + c = 0 có nghiệm khi nào?',
    subject: 'Toán',
    difficulty: 'EASY',
    tags: ['phương trình', 'bậc hai'],
  },
  {
    id: '2',
    content: 'Định luật Newton thứ hai phát biểu như thế nào?',
    subject: 'Vật lý',
    difficulty: 'MEDIUM',
    tags: ['cơ học', 'newton'],
  },
  {
    id: '3',
    content: 'Liên kết cộng hoá trị là gì?',
    subject: 'Hoá học',
    difficulty: 'HARD',
    tags: ['liên kết', 'hoá học'],
  },
];

export const studentClasses: ClassSummary[] = [
  {
    id: '1',
    name: 'Toán cao cấp',
    subject: 'Toán',
    schoolYear: '2025-2026',
    code: 'EDU-ABC123',
    teacherName: 'Nguyễn Văn A',
    studentCount: 35,
    assignmentCount: 3,
    pendingAssignments: 1,
  },
  {
    id: '2',
    name: 'Vật lý đại cương',
    subject: 'Vật lý',
    schoolYear: '2025-2026',
    code: 'EDU-XYZ789',
    teacherName: 'Lê Thị X',
    studentCount: 42,
    assignmentCount: 2,
    pendingAssignments: 0,
  },
  {
    id: '3',
    name: 'Hoá học hữu cơ',
    subject: 'Hoá học',
    schoolYear: '2025-2026',
    code: 'EDU-QWE456',
    teacherName: 'Trần Minh Y',
    studentCount: 28,
    assignmentCount: 1,
    pendingAssignments: 1,
  },
  {
    id: '4',
    name: 'Sinh học tế bào',
    subject: 'Sinh học',
    schoolYear: '2025-2026',
    code: 'EDU-RTY321',
    teacherName: 'Phạm Thu Z',
    studentCount: 31,
    assignmentCount: 4,
    pendingAssignments: 1,
  },
];

export const studentAssignments: AssignmentSummary[] = [
  {
    id: '1',
    title: 'Bài tập chương 3',
    description: '',
    deadline: '2025-04-25T23:59:00',
    classNames: ['Toán cao cấp'],
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: true,
    latePenaltyPct: 10,
  },
  {
    id: '2',
    title: 'Thực hành thí nghiệm',
    description: '',
    deadline: '2025-04-20T23:59:00',
    classNames: ['Vật lý đại cương'],
    submitted: true,
    submitStatus: 'ON_TIME',
    gradeStatus: 'GRADED',
    score: 8,
    maxScore: 10,
    allowLate: false,
    latePenaltyPct: 0,
  },
  {
    id: '3',
    title: 'Luận văn ngắn',
    description: '',
    deadline: '2025-04-30T23:59:00',
    classNames: ['Hoá học hữu cơ'],
    submitted: true,
    submitStatus: 'LATE',
    gradeStatus: 'PENDING',
    score: null,
    maxScore: 10,
    allowLate: true,
    latePenaltyPct: 20,
  },
  {
    id: '4',
    title: 'Ôn tập giữa kỳ',
    description: '',
    deadline: '2025-04-15T23:59:00',
    classNames: ['Toán cao cấp'],
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: false,
    latePenaltyPct: 0,
  },
  {
    id: '5',
    title: 'Báo cáo sinh học',
    description: '',
    deadline: '2025-05-10T23:59:00',
    classNames: ['Sinh học tế bào'],
    submitted: false,
    submitStatus: null,
    gradeStatus: null,
    score: null,
    maxScore: 10,
    allowLate: true,
    latePenaltyPct: 15,
  },
];

export const studentResults: ResultSummary[] = [
  {
    id: '1',
    examTitle: 'Giữa kỳ Toán',
    score: 8,
    maxScore: 10,
    totalCorrect: 16,
    totalQuestions: 20,
    status: 'GRADED',
    createdAt: '2025-04-15',
  },
  {
    id: '2',
    examTitle: 'Cuối kỳ Vật lý',
    score: 7.5,
    maxScore: 10,
    totalCorrect: 15,
    totalQuestions: 20,
    status: 'GRADED',
    createdAt: '2025-04-12',
  },
  {
    id: '3',
    examTitle: 'Kiểm tra Hoá',
    score: 0,
    maxScore: 10,
    totalCorrect: 0,
    totalQuestions: 20,
    status: 'NEEDS_REVIEW',
    createdAt: '2025-04-10',
  },
  {
    id: '4',
    examTitle: 'Sinh học giữa kỳ',
    score: 9,
    maxScore: 10,
    totalCorrect: 18,
    totalQuestions: 20,
    status: 'GRADED',
    createdAt: '2025-04-05',
  },
];

export const resultDetails: ResultDetailRow[] = [
  {
    questionNumber: 1,
    detectedAnswer: 'A',
    finalAnswer: 'A',
    correctAnswer: 'A',
    isCorrect: true,
    needsReview: false,
  },
  {
    questionNumber: 2,
    detectedAnswer: 'B',
    finalAnswer: 'B',
    correctAnswer: 'C',
    isCorrect: false,
    needsReview: false,
  },
  {
    questionNumber: 3,
    detectedAnswer: 'C',
    finalAnswer: 'C',
    correctAnswer: 'C',
    isCorrect: true,
    needsReview: false,
  },
  {
    questionNumber: 4,
    detectedAnswer: null,
    finalAnswer: null,
    correctAnswer: 'D',
    isCorrect: false,
    needsReview: true,
    reviewReason: 'Không phát hiện được câu trả lời',
  },
  {
    questionNumber: 5,
    detectedAnswer: 'A',
    finalAnswer: 'B',
    correctAnswer: 'A',
    isCorrect: false,
    needsReview: true,
    reviewReason: 'Phát hiện mờ, có thể nhầm',
  },
  {
    questionNumber: 6,
    detectedAnswer: 'D',
    finalAnswer: 'D',
    correctAnswer: 'D',
    isCorrect: true,
    needsReview: false,
  },
  {
    questionNumber: 7,
    detectedAnswer: 'A',
    finalAnswer: 'A',
    correctAnswer: 'A',
    isCorrect: true,
    needsReview: false,
  },
  {
    questionNumber: 8,
    detectedAnswer: 'C',
    finalAnswer: 'C',
    correctAnswer: 'B',
    isCorrect: false,
    needsReview: false,
  },
];

export const studentRemarks: RemarkSummary[] = [
  {
    id: '1',
    examTitle: 'Giữa kỳ Toán',
    questionNumber: 5,
    reason: 'Em chọn đáp án A nhưng hệ thống nhận là B',
    status: 'PENDING',
    createdAt: '2025-04-18',
  },
  {
    id: '2',
    examTitle: 'Cuối kỳ Vật lý',
    questionNumber: 12,
    reason: 'Câu này em tô rõ ràng mà bị nhận sai',
    status: 'APPROVED',
    teacherComment: 'Đã kiểm tra và cập nhật điểm',
    createdAt: '2025-04-16',
  },
  {
    id: '3',
    examTitle: 'Kiểm tra Hoá',
    questionNumber: 3,
    reason: 'Phần tô bị nhòe',
    status: 'REJECTED',
    teacherComment: 'Kiểm tra lại, phiếu gốc không có vấn đề',
    createdAt: '2025-04-14',
  },
];

export const progressPoints: ProgressPoint[] = [
  { date: '01/03', score: 6, examTitle: 'KT 15p Toán' },
  { date: '15/03', score: 7, examTitle: 'Giữa kỳ Sinh' },
  { date: '01/04', score: 7.5, examTitle: 'Cuối kỳ Vật lý' },
  { date: '10/04', score: 6.5, examTitle: 'KT Hoá' },
  { date: '15/04', score: 8, examTitle: 'Giữa kỳ Toán' },
  { date: '18/04', score: 9, examTitle: 'Sinh giữa kỳ' },
];

export const adminUsers: UserSummary[] = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    email: 'a@edu.vn',
    role: 'TEACHER',
    studentCode: null,
    isActive: true,
  },
  {
    id: '2',
    name: 'Trần Thị B',
    email: 'b@edu.vn',
    role: 'STUDENT',
    studentCode: 'STU001',
    isActive: true,
  },
  {
    id: '3',
    name: 'Lê Văn C',
    email: 'c@edu.vn',
    role: 'STUDENT',
    studentCode: 'STU002',
    isActive: false,
  },
  {
    id: '4',
    name: 'Phạm Minh D',
    email: 'd@edu.vn',
    role: 'STUDENT',
    studentCode: 'STU003',
    isActive: true,
  },
  {
    id: '5',
    name: 'Hoàng E',
    email: 'e@edu.vn',
    role: 'ADMIN',
    studentCode: null,
    isActive: true,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: '1',
    type: 'assignment',
    title: 'Bài tập mới trong lớp Toán cao cấp',
    body: 'Giáo viên đã thêm bài tập "Bài tập chương 3" — hạn nộp 25/04/2025.',
    time: '5 phút trước',
    read: false,
  },
  {
    id: '2',
    type: 'result',
    title: 'Kết quả bài thi đã có',
    body: 'Điểm Giữa kỳ Toán của bạn đã được công bố: 8.0/10.',
    time: '1 giờ trước',
    read: false,
  },
  {
    id: '3',
    type: 'remark',
    title: 'Phúc khảo đã được duyệt',
    body: 'Yêu cầu phúc khảo câu 12 bài Vật lý đã được giáo viên chấp thuận.',
    time: '3 giờ trước',
    read: true,
  },
  {
    id: '4',
    type: 'system',
    title: 'Cập nhật hệ thống',
    body: 'EduScan vừa được cập nhật lên phiên bản 2.1 với nhiều tính năng mới.',
    time: 'Hôm qua',
    read: true,
  },
  {
    id: '5',
    type: 'result',
    title: 'Chấm điểm hoàn tất',
    body: 'Bài Cuối kỳ Vật lý đã được chấm xong. Nhấn để xem chi tiết.',
    time: '2 ngày trước',
    read: true,
  },
];
