from __future__ import annotations

import argparse

from app.dataset.sampling import sample_inventory


def main() -> None:
    parser = argparse.ArgumentParser(description="Sample a smaller OMR dataset subset grouped by layout.")
    parser.add_argument("inventory_path", help="Path to the inventory JSON generated by inspect_dataset.py")
    parser.add_argument("output_dir", help="Output directory for the sampled subset")
    parser.add_argument("--per-layout", type=int, default=20, help="Maximum number of images to sample per layout")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducible sampling")
    args = parser.parse_args()

    summary = sample_inventory(
        inventory_path=args.inventory_path,
        output_dir=args.output_dir,
        per_layout=args.per_layout,
        seed=args.seed,
    )

    print(f"Subset written to: {summary['output_dir']}")
    print("Selected images:")
    for layout, count in sorted(summary["selected"].items()):
        print(f"  - {layout}: {count}")


if __name__ == "__main__":
    main()
