export const vi = {
  meta: {
    appName: 'EduScan',
    version: 'v2.0 · 2025',
    slogan: 'Hệ thống quản lý giáo dục thông minh',
  },
  roles: {
    TEACHER: 'Giáo viên',
    STUDENT: 'Học sinh',
    ADMIN: 'Quản trị viên',
  },
  language: {
    vi: 'Tiếng Việt',
    en: 'English',
  },
  common: {
    buttons: {
      login: 'Đăng nhập',
      loggingIn: 'Đang đăng nhập...',
      backToHome: 'Trang chủ',
      back: 'Quay lại',
      cancel: 'Huỷ',
      confirm: 'Xác nhận',
      create: 'Tạo mới',
      createClass: 'Tạo lớp',
      createExam: 'Tạo đề thi',
      createQuestion: 'Tạo câu hỏi',
      createAssignment: 'Tạo bài tập',
      joinClass: 'Tham gia',
      startScan: 'Bắt đầu quét',
      submitAssignment: 'Nộp bài',
      sendRequest: 'Gửi yêu cầu',
      approve: 'Duyệt',
      reject: 'Từ chối',
      deactivate: 'Vô hiệu hoá',
      logout: 'Đăng xuất',
      save: 'Lưu thay đổi',
      viewDetails: 'Xem chi tiết',
      exportReport: 'Xuất báo cáo',
      switchLanguage: 'Đổi ngôn ngữ',
    },
    labels: {
      home: 'Trang chủ',
      notifications: 'Thông báo',
      profile: 'Cá nhân',
      scoreUnit: 'điểm',
      total: 'Tổng cộng',
      teacher: 'GV',
      question: 'Câu',
      loading: 'Đang tải',
      recent: 'Gần đây',
      overview: 'Tổng quan',
      today: 'Hôm nay',
      active: 'Đang hoạt động',
      inactive: 'Đã khoá',
      all: 'Tất cả',
      optional: 'Tuỳ chọn',
    },
    search: {
      classes: 'Tìm lớp học...',
      exams: 'Tìm đề thi...',
      assignments: 'Tìm bài tập...',
      questions: 'Tìm câu hỏi...',
      users: 'Tìm theo tên, email...',
    },
    placeholders: {
      email: 'email@example.com',
      password: 'Nhập mật khẩu',
      className: 'Ví dụ: Toán 10A1',
      subject: 'Ví dụ: Toán',
      examTitle: 'Ví dụ: Giữa kỳ Toán',
      questionNumber: 'Ví dụ: 5',
      schoolYear: '2025-2026',
      classCode: 'Ví dụ: EDU-ABC123',
      studentLookup: 'Nhập email hoặc mã học sinh',
      questionContent: 'Nhập nội dung câu hỏi...',
      optionA: 'Nhập đáp án A',
      optionB: 'Nhập đáp án B',
      optionC: 'Nhập đáp án C',
      optionD: 'Nhập đáp án D',
      fileUrl: 'Nhập URL tệp bài làm',
      remarkReason: 'Mô tả lý do yêu cầu phúc khảo...',
      assignmentTitle: 'Ví dụ: Bài tập chương 3',
      assignmentDescription: 'Hướng dẫn làm bài...',
      personName: 'Nhập họ tên',
      studentCode: 'VD: STU001',
      dateTime: 'Chọn thời gian',
      maxScore: 'Ví dụ: 10',
      role: 'Chọn vai trò',
    },
    messages: {
      loginEmpty: 'Vui lòng nhập đầy đủ email và mật khẩu',
      loginPasswordShort: 'Mật khẩu phải có ít nhất 6 ký tự',
      emptyClasses: 'Không tìm thấy lớp học nào',
      emptyExams: 'Không tìm thấy đề thi nào',
      emptyAssignments: 'Không có bài tập nào',
      emptyNotifications: 'Chưa có thông báo nào',
      emptyQuestions: 'Không có câu hỏi phù hợp',
      emptyRemarks: 'Không có yêu cầu phúc khảo nào',
      emptyUsers: 'Không tìm thấy tài khoản phù hợp',
      emptyResults: 'Chưa có kết quả nào',
      expiredAssignment: 'Đã quá hạn nộp bài',
      lateAllowed: 'Cho phép nộp trễ, có trừ điểm',
      uploadHint: 'JPEG, PNG, WebP • Tối đa 50 ảnh',
      assignmentUploadHint:
        'Tải tệp lên Google Drive, Dropbox... rồi dán liên kết vào đây',
      assignmentUploadHintAlt:
        'Tải tệp lên Google Drive, Dropbox, v.v. rồi dán liên kết vào đây',
      deactivateWarning:
        'Bạn có chắc muốn vô hiệu hoá tài khoản này? Người dùng sẽ không thể đăng nhập.',
      sessionActive: 'Phiên đăng nhập đang hoạt động',
    },
    sections: {
      functions: 'Chức năng',
      classes: 'Lớp học',
      assignments: 'Bài tập',
      info: 'Thông tin',
      history: 'Lịch sử',
      resultDetails: 'Chi tiết từng câu',
      systemManagement: 'Quản lý hệ thống',
      trend: 'Xu hướng điểm số',
      scoreHistory: 'Lịch sử điểm',
    },
    form: {
      email: 'Email',
      password: 'Mật khẩu',
      className: 'Tên lớp',
      subject: 'Môn học',
      schoolYear: 'Năm học',
      assignmentTitle: 'Tiêu đề bài tập',
      assignmentDescription: 'Mô tả',
      deadline: 'Hạn nộp',
      maxScore: 'Điểm tối đa',
      allowLate: 'Cho phép nộp trễ',
      latePenaltyPct: 'Phần trăm trừ điểm (%)',
      exam: 'Đề thi',
      questionNumber: 'Số câu',
      examTitle: 'Tên đề thi',
      reason: 'Lý do',
      content: 'Nội dung câu hỏi',
      correctAnswer: 'Đáp án đúng',
      role: 'Vai trò',
      fullName: 'Họ và tên',
      studentCode: 'Mã học sinh',
      assignmentFileUrl: 'Liên kết tệp bài làm',
    },
    tabs: {
      students: 'Học sinh',
      assignments: 'Bài tập',
      info: 'Thông tin',
      pending: 'Chưa nộp',
      overdue: 'Quá hạn',
      submitted: 'Đã nộp',
      approved: 'Đã duyệt',
      rejected: 'Từ chối',
      pendingReview: 'Chờ duyệt',
    },
    statuses: {
      GRADED: 'Đã chấm',
      NEEDS_REVIEW: 'Cần xem xét',
      FAILED: 'Lỗi',
      PENDING: 'Chờ xử lý',
      PROCESSING: 'Đang xử lý',
      COMPLETED: 'Hoàn thành',
      PARTIAL_FAILED: 'Thành công một phần',
      ON_TIME: 'Đúng hạn',
      LATE: 'Nộp trễ',
      APPROVED: 'Đã duyệt',
      REJECTED: 'Từ chối',
      EASY: 'Dễ',
      MEDIUM: 'Trung bình',
      HARD: 'Khó',
    },
  },
  auth: {
    title: 'Đăng nhập',
    welcome: 'Chào mừng trở lại! Vui lòng đăng nhập.',
    demoTitle: 'Tài khoản demo',
  },
  teacher: {
    dashboard: {
      greeting: 'Xin chào,',
      subtitle: 'Năm học 2025-2026',
      metrics: {
        classes: 'Lớp học',
        exams: 'Đề thi',
        remarks: 'Phúc khảo',
      },
      modules: {
        classes: 'Lớp học',
        exams: 'Đề thi',
        omr: 'Quét OMR',
        remarks: 'Phúc khảo',
        questions: 'Ngân hàng câu hỏi',
        stats: 'Thống kê',
      },
      moduleCounts: {
        classes: '5 lớp',
        exams: '12 đề',
        omr: '3 đợt',
        remarks: '3 yêu cầu',
        questions: '48 câu',
        stats: 'Xem báo cáo',
      },
    },
    classes: {
      title: 'Lớp học',
      createTitle: 'Tạo lớp mới',
      addStudent: 'Thêm học sinh',
      studentsByCode: 'Email, mã học sinh, hoặc ID',
      studentCountSuffix: 'học sinh',
      updateInfo: 'Cập nhật thông tin',
      codeCopied: 'Mã lớp',
      newAssignment: 'Thêm bài tập mới',
      noAssignments: 'Chưa có bài tập nào',
      viewSubmissions: 'Xem bài nộp',
      deleteAssignment: 'Xoá bài tập',
    },
    exams: {
      title: 'Đề thi',
      lockedHint: 'Đề thi này đã có dữ liệu chấm',
    },
    omr: {
      title: 'Quét phiếu OMR',
      uploadTitle: 'Tải ảnh phiếu trả lời',
      uploadSubtitle: 'Tối đa 50 ảnh mỗi lần',
      historyTitle: 'Lịch sử quét',
      selectExam: 'Chọn đề thi',
      selectImages: 'Chạm để chọn ảnh',
    },
    assignments: {
      title: 'Bài tập',
    },
    remarks: {
      title: 'Phúc khảo',
      detailTitle: 'Chi tiết phúc khảo',
      teacherComment: 'Nhận xét của giáo viên',
    },
    questions: {
      title: 'Ngân hàng câu hỏi',
      createTitle: 'Tạo câu hỏi mới',
      optionLabel: 'Đáp án',
    },
    report: {
      title: 'Xuất báo cáo',
      description: 'Xuất báo cáo lớp theo định dạng PDF hoặc XLSX',
      formatPdf: 'PDF',
      formatXlsx: 'XLSX',
      scopeAll: 'Toàn bộ dữ liệu',
    },
  },
  student: {
    dashboard: {
      greeting: 'Xin chào,',
      subtitle: 'Năm học 2025-2026',
      metrics: {
        average: 'Điểm TB',
        exams: 'Bài thi',
        rank: 'Xếp loại',
      },
      modules: {
        classes: 'Lớp học',
        results: 'Kết quả',
        assignments: 'Bài tập',
        remarks: 'Phúc khảo',
        progress: 'Tiến độ học tập',
      },
      moduleCounts: {
        classes: '4 lớp đang học',
        results: '12 bài thi',
        assignments: '3 chưa nộp',
        remarks: '1 đang chờ',
        progress: 'TB: 7.8',
      },
    },
    classes: {
      title: 'Lớp học',
      joinTitle: 'Tham gia lớp học',
      joinSubtitle: 'Nhập mã lớp do giáo viên cung cấp',
      joinNewClass: 'Tham gia lớp học mới',
      activeClasses: 'lớp đang tham gia',
      pendingAssignmentsSuffix: 'bài chưa nộp',
      classInfoTitle: 'Thông tin lớp',
    },
    results: {
      title: 'Kết quả học tập',
      average: 'Trung bình',
      highest: 'Cao nhất',
      totalExams: 'Tổng bài',
      viewProgress: 'Xem biểu đồ tiến độ',
      remarkAction: 'Phúc khảo',
      resultCodePrefix: 'Mã đề',
    },
    assignments: {
      title: 'Bài tập',
      subtitle: 'Theo dõi và nộp bài tập của bạn',
    },
    remarks: {
      title: 'Phúc khảo của tôi',
      createTitle: 'Gửi yêu cầu phúc khảo',
      teacherComment: 'Nhận xét của giáo viên',
      reasonTitle: 'Lý do phúc khảo',
    },
    progress: {
      title: 'Biểu đồ tiến độ',
      subtitle: 'Điểm số qua các bài thi',
      summaryAverage: 'Điểm TB',
      summaryHighest: 'Cao nhất',
      summaryGoal: 'Mục tiêu',
    },
  },
  admin: {
    dashboard: {
      title: 'Quản trị viên',
      subtitle: 'Toàn quyền quản lý hệ thống',
      metrics: {
        teachers: 'Giáo viên',
        students: 'Học sinh',
        classes: 'Lớp học',
      },
      modules: {
        users: 'Tài khoản',
        classes: 'Lớp học',
        stats: 'Thống kê',
        settings: 'Cài đặt',
      },
      moduleCounts: {
        users: '156 người dùng',
        classes: '18 lớp đang hoạt động',
        stats: 'Xem báo cáo',
        settings: 'Hệ thống',
      },
    },
    users: {
      title: 'Quản lý tài khoản',
      createTitle: 'Tạo tài khoản mới',
    },
  },
  shared: {
    profile: {
      title: 'Cá nhân',
      personalInfo: 'Thông tin cá nhân',
      personalInfoSubtitle: 'Xem và chỉnh sửa thông tin',
      notifications: 'Thông báo',
      notificationSubtitle: 'Quản lý thông báo',
      language: 'Ngôn ngữ',
      security: 'Bảo mật',
      securitySubtitle: 'Đổi mật khẩu',
      logoutSubtitle: 'Thoát khỏi tài khoản',
      studentRank: 'Khá',
      teacherOmrCount: 'OMR',
    },
    notifications: {
      title: 'Thông báo',
      unread: 'chưa đọc',
    },
  },
} as const;
